### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by devjiwonchoi** [darkroomstudio/harumada-front#9]
# Screen Development

## Common Components
- [ ] Bottom Bar
- [ ] Top
- [ ] Edit Daily Motivation Message
- [ ] Show Today's Notifications
- [ ] Card List

## Notifications
- [ ] Text / Word Counter
- [ ] Check Notifications

## Goals
- [ ] In Progress/Scheduled/Completed Filtering
- [ ] Goal List
- [ ] Add Goal

## Goal Details
- [ ] Language Status
- [ ] Title
- [ ] Days/Months Count
- [ ] Participant User Avatars
- [ ] Daily Progress Percentage
- [ ] Change Participant User Problem Language Status
- [ ] Detailed Information
  - [ ] Current Progress Notification
  - [ ] Target Date
  - [ ] Current Stage
  - [ ] Commitment Message
- [ ] Attendance Record
  - [ ] Attendance Notification
  - [ ] Attendance Date
  - [ ] Attendance Status
  - [ ] Avatar
  - [ ] Attendance Log
    - [ ] Avatar
    - [ ] Attendance Notification
    - [ ] Attendance Date
    - [ ] Attendance Status

## Add Goal
- [ ] Invitation Code Check
  - [ ] With Invitation Code
    - [ ] Code Input
    - [ ] Check Inviting User
    - [ ] Invitation Content
    - [ ] Join vs Decline
      - [ ] Decline Toast
      - [ ] To Goal Screen
  - [ ] Without Invitation Code
    - [ ] Goal Setting
    - [ ] Goal Period Setting
    - [ ] Start Date Setting
    - [ ] Goal Detailed Description
    - [ ] Commitment Message
    - [ ] Goal Screen View Notification
      - [ ] Send Share Button

## Login/Sign Up Screen
- [ ] Google Login

## Profile
- [ ] Edit Information
  - [ ] Nickname
  - [ ] Self Introduction
  - [ ] Name
  - [ ] Self Introduction
  - [ ] My Goals
    - [ ] In Progress
    - [ ] Completed
  - [ ] Personality
    - [ ] Avatar
    - [ ] App Version
    - [ ] Send Feedback
  - [ ] Commitment Profile Modal
    - [ ] Profile Picture
    - [ ] Name
    - [ ] Self Introduction
    - [ ] Number of Goals in Progress
    - [ ] Number of Completed Goals
